package com.prorf.domains.rf.nodes

import com.prorf.domains.rf.RfPort
import com.prorf.domains.rf.bandwidthMhz
import com.prorf.domains.rf.dbm
import com.prorf.domains.rf.kelvin
import com.prorf.engineering.quantity.PhysicalUnit
import com.prorf.engineering.quantity.Quantity
import com.prorf.platform.execution.NodeExecutor
import com.prorf.platform.graph.NodeDefinition
import com.prorf.platform.graph.ParameterDefinition
import com.prorf.platform.graph.PortDefinition
import kotlin.math.log10
import kotlin.math.max

/**
 * Thermal noise source — models noise generated by a resistive element.
 * Outputs noise power P = kTB (dBm).
 */
object NoiseSource {
    const val TYPE_ID = "rf.noise_source"

    private const val BOLTZMANN_J_PER_K = 1.380649e-23

    val definition = NodeDefinition(
        typeId = TYPE_ID,
        displayName = "Noise Source",
        description = "Thermal noise source — outputs P = kTB noise power floor in dBm",
        inputs = emptyList(),
        outputs = listOf(
            PortDefinition(RfPort.RF_OUT, "RF Out", "power_dbm"),
            PortDefinition("noisePowerDbm", "Noise Power", "power_dbm"),
        ),
        parameters = listOf(
            ParameterDefinition("noiseTemperatureK", "Noise Temperature (K)", "quantity", Quantity(290.0, PhysicalUnit.KELVIN)),
            ParameterDefinition("bandwidthMHz", "Bandwidth (MHz)", "quantity", Quantity(36.0, PhysicalUnit.BANDWIDTH_MHZ)),
        ),
    )

    fun noisePowerDbm(temperatureK: Double, bandwidthMHz: Double): Double {
        val tempK = max(temperatureK, 0.1)
        val bwHz = max(bandwidthMHz, 0.001) * 1e6
        return 10.0 * log10(BOLTZMANN_J_PER_K * tempK * bwHz) + 30.0
    }

    class Executor : NodeExecutor {
        override val typeId = TYPE_ID
        override fun execute(inputs: Map<String, Any>, parameters: Map<String, Any>): Map<String, Any> {
            val tempK = parameters.kelvin("noiseTemperatureK", 290.0).value
            val bwMHz = parameters.bandwidthMhz("bandwidthMHz", 36.0).value
            val power = noisePowerDbm(tempK, bwMHz)
            val noisePower = dbm(power)
            return mapOf(
                RfPort.RF_OUT to noisePower,
                "noisePowerDbm" to noisePower,
            )
        }
    }
}
